// client/src/lib/invoicePdf.js
import jsPDF from "jspdf";

export function generateInvoicePdf(invoice) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const safe = value => (value === undefined || value === null ? "" : String(value));

  const items = invoice.items || [];
  const number = safe(invoice.number) || "-";
  const date = safe(invoice.date) || "-";
  const customerName = safe(invoice.customer?.name);
  const customerEmail = safe(invoice.customer?.email);
  const customerAddress = safe(invoice.customer?.address);

  // ========= HEADER =========
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("CS308 TechHub Store", margin, y);
  doc.setFontSize(22);
  doc.text("INVOICE", pageWidth - margin, y, { align: "right" });

  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ========= INVOICE + CUSTOMER INFO =========
  const midX = margin + contentWidth / 2;

  // Invoice info (left)
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Invoice Details", margin, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(`Invoice No: ${number}`, margin, y);
  y += 5;
  doc.text(`Date: ${date}`, margin, y);

  // Customer info (right)
  let rightY = y - 11; // align with "Invoice Details" line
  doc.setFont("helvetica", "bold");
  doc.text("Billed To", midX, rightY);
  doc.setFont("helvetica", "normal");
  rightY += 6;
  if (customerName) {
    doc.text(customerName, midX, rightY);
    rightY += 5;
  }
  if (customerEmail) {
    doc.text(customerEmail, midX, rightY);
    rightY += 5;
  }
  if (customerAddress) {
    // Address uzun olabilir, satırlara bölelim
    const addrLines = doc.splitTextToSize(customerAddress, contentWidth / 2);
    doc.text(addrLines, midX, rightY);
    rightY += addrLines.length * 5;
  }

  // Y'yi sağ taraftaki blokla hizala
  y = Math.max(y + 10, rightY + 5);

  // ========= ITEMS TABLE =========
  y += 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Items", margin, y);
  y += 4;

  // Table header background
  const headerHeight = 8;
  const rowHeight = 7;

  const colDescX = margin + 2;
  const colQtyX = margin + contentWidth * 0.6;
  const colPriceX = margin + contentWidth * 0.75;
  const colTotalX = margin + contentWidth * 0.9;

  doc.setFillColor(245, 245, 245);
  doc.rect(margin, y, contentWidth, headerHeight, "F");

  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text("Description", colDescX, y + 5);
  doc.text("Qty", colQtyX, y + 5);
  doc.text("Price", colPriceX, y + 5);
  doc.text("Line Total", colTotalX, y + 5, { align: "right" });

  y += headerHeight;

  doc.setTextColor(0);
  doc.setFont("helvetica", "normal");

  let subtotal = 0;

  if (items.length === 0) {
    y += rowHeight;
    doc.text("No items.", colDescX, y);
    y += rowHeight;
  } else {
    items.forEach(item => {
      const name = safe(item.name);
      const qty = Number(item.qty || item.quantity || 0);
      const price = Number(item.price || 0);
      const lineTotal = qty * price;
      subtotal += lineTotal;

      y += rowHeight;

      // Sayfa sonuna yaklaştıysak yeni sayfa aç
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      // Description (wrap)
      const maxDescWidth = colQtyX - colDescX - 4;
      const descLines = doc.splitTextToSize(name, maxDescWidth);
      doc.text(descLines, colDescX, y);

      // aynı satırda qty/price/total
      doc.text(String(qty), colQtyX, y);
      doc.text(`$${price.toFixed(2)}`, colPriceX, y);
      doc.text(`$${lineTotal.toFixed(2)}`, colTotalX, y, { align: "right" });

      // çok satırlı açıklama için y’yi ayarla
      y += (descLines.length - 1) * 5;
    });
    y += rowHeight;
  }

  // ========= TOTALS =========
  const grandTotal = Number(invoice.total ?? subtotal);

  // çizgi
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  const labelX = colPriceX;
  const valueX = colTotalX;

  doc.setFont("helvetica", "bold");
  doc.text("Subtotal:", labelX, y);
  doc.text(`$${subtotal.toFixed(2)}`, valueX, y, { align: "right" });
  y += 6;

  doc.setFontSize(11);
  doc.text("Total:", labelX, y);
  doc.setFontSize(12);
  doc.text(`$${grandTotal.toFixed(2)}`, valueX, y, { align: "right" });

  y += 14;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(
    "Thank you for your purchase! This invoice was generated by the CS308 Store.",
    margin,
    y
  );

  // İstersen burada doc.save(...) değil, doc'u döndürüyoruz
  return doc;
}
